### ISSUE TITLE
Remote server plugin

### ISSUE THREAD

**Issue by vzahradnik** [TcMenu/tcMenu#491]
**Is your feature request related to a problem? Please describe.**
Create a new TcMenu plugin which provides remote server support.

**Describe the solution you'd like**
Allow the plugin to set either IP or DNS domain. Also allow to override this config using build flags, similarly how users can override project name. This is required as users might want to connect to different services based on the build configuration - a staging server for testing and a production server for release.

**Comment by davetcc** [comment]
Can you try it @vzahradnik  and see if it works OK for you, I tested it on ESP32 and it built and worked.

**Comment by vzahradnik** [comment]
I will try it and report back here. Thanks!

**Comment by vzahradnik** [comment]
My first observation is regarding the IP address. Is there a way to use a compile flag instead of hardcoding the ip address in the field?

For example, I want to set one IP address for the debug environment and another one for production environment.

DNS resolver where I could type domain name would be even better but we can explore this feature later.

I will have a detailed look at the plugin during the week.

**Comment by vzahradnik** [comment]
Another observation: TcMenu tries to connect to remote even though the IP is not reachable. As part of the optimization, we should implement something like this:

- Check if the network connection is established at all
- If it is, try to connect to the remote server
- If the connection is not successful, implement a timeout of 5 seconds
- After the second unsuccessful connection, double the timeout to 10 seconds, etc... up to 5 minutes (configurable as a global TcMenu variable)
- Once the connection is established, reset the timeout

This solution will - I believe - save some energy when running from battery and will reduce the clutter in logs a lot.
![image](https://github.com/user-attachments/assets/20eeda15-907d-4a44-b4bc-4d86560f9109)

**Comment by vzahradnik** [comment]
Long term, I'd like to have a networking module/library ready to handle this for the whole system.

**Comment by vzahradnik** [comment]
TcMenuJavaAPI in Maven Central is still on version 4.2.2 and doesn't have support for this feature.

**Comment by vzahradnik** [comment]
I will check the encryption code during the weekend. Besides those small optimization issues, the plugin works great!

**Comment by davetcc** [comment]
> My first observation is regarding the IP address. Is there a way to use a compile flag instead of hardcoding the ip address in the field?
> 
> For example, I want to set one IP address for the debug environment and another one for production environment.
> 
> DNS resolver where I could type domain name would be even better but we can explore this feature later.
> 
> I will have a detailed look at the plugin during the week.

You can now set the address either to be hardwired, variable, or compile flag

**Comment by davetcc** [comment]
> TcMenuJavaAPI in Maven Central is still on version 4.2.2 and doesn't have support for this feature.

It is now updated, this was due to the account needing an update.

**Comment by davetcc** [comment]
>Alternatively, respect the heartbeat global config and initiate the session not sooner than the HEARTBEAT_INTERVAL value.

For now let's do this, and look into a proper networking library as discussed.

**Comment by davetcc** [comment]
I think most of the immediate issues are now resolved by 4.4, I'm going to close for now, and we can open issues for anything new that we find.
