### ISSUE TITLE
Migrate libraries to TcMenuLog

### ISSUE THREAD

**Issue by vzahradnik** [TcMenu/tcMenu#505]
**Is your feature request related to a problem? Please describe.**
Migrate all embedded libraries to use TcMenuLog as their dependency. We are refactoring the code and the text utils and logging doesn't belong into IoAbstraction. For now we moved the files into a new library and will go from there.

**Describe the solution you'd like**
Update each library using the text utils to have TcMenuLog as the dependency. This migration can be done once TcMenuLog is published into PlatformIO registry and Arduino library registry.

**Comment by davetcc** [comment]
The testing is now concluded, a release will take place shortly
